---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: realworld-backend
  namespace: realworld
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:stg-*
spec:
  releaseName: realworld-backend
  chart:
    repository: https://realworld.azurecr.io/helm/v1/repo/
    name: realworld-backend
    version: 0.1.1
  values:
    image:
      repository: realworld.azurecr.io/backend/realworld-backend
      tag: stg-6df42957762c89cda02a2ada2c32ea2810e070f4
