---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: realworld-backend
  namespace: realworld
  fluxcd.io/automated: "true"
  fluxcd.io/tag.chart-image: glob:stg-*
spec:
  releaseName: realworld-backend
  chart:
    repository: https://realworld.azurecr.io/helm/v1/repo/
    name: realworld-backend
    version: 0.1.1
  values:
    image:
      repository: realworld.azurecr.io/backend/realworld-backend
      tag: "stg-901c1419068a451286cae279b79ca3fa61ea0f50"
